### PR TITLE
RingpopHandler: update RelayRequest usage for TChannel 2.7.0

### PR DESCRIPTION
**Pull request by jcorbin**
Update to work past https://github.com/uber/tchannel/pull/1222 which shipped in TChannel 2.7.0.

r @jwolski

### CODE REVIEW

**Comment by jcorbin** [comment]
Going to dog food this by deploying https://github.com/uber/tchannel/pull/1232 to prod before asking you to merge or version this upgrade :-)

**Comment by jcorbin** [comment]
Okay, dog fooding in production was a success, merge this at your own rate and schedule, we can continue to deploy off a branch until you're ready to say "users upgrading to 10.X need to be also on TChannel >= 2.7.0" (or even 11 if you must, but it's a rather nominal change, your call :-) )

**Comment by jwolski** [comment]
thanks @jcorbin

**Comment by jwolski** [comment]
Oops. I should have been a bit more careful here. I merged without double-checking that everything was legit. TChannel >= 2.7.0 does not appear to be published to NPM. @jcorbin

**Comment by jcorbin** [comment]
Sorry about that, I should've been clearer: 2.7.0 is published under the alpha tag, so that people don't get it by default (in the interest of waiting for ringpop to get ready to ship a compatible change e.g.):
```
$ npm dist-tag ls tchannel
npm http request GET https://registry.npmjs.org/-/package/tchannel/dist-tags
npm http 200 https://registry.npmjs.org/-/package/tchannel/dist-tags
alpha: 2.7.0
latest: 2.6.6
```

So you can get it by `npm install tchannel@alpha` or `npm install tchannel@2.7.0`.  I'll wait for you to have published (maybe also under a non-latest tag also?) of ringpop that is 2.7.0 safe, and then we can update our "latest" npm tags in concert.

**Pull request merged**
