### PR TITLE
Travis CI integration

### PR DESCRIPTION
**Pull request by jwolski**
@Raynos @robskillington

### CODE REVIEW

**Comment by robskillington** [comment]
Might you want:

```
notifications:
  email: false
```
?  The emails are quite the spam.  As per https://github.com/uber/jetstream/blob/master/.travis.yml

Also you might need to flip a switch somewhere, it should've built this PR and posted back so something might not be configured just yet.

**Comment by jwolski** [comment]
thx

**Comment by Raynos** [comment]
@jwolski 

See:

 - https://github.com/uber/uber-ngen/blob/master/templates/uber/content/.travis.yml
 - https://github.com/uber/uber-ngen/blob/master/templates/uber/content/package.json#L40

We want to apply these. Especially the coverage stuff for integrating with coveralls.

**Comment by Raynos** [comment]
lgtm.

**Pull request merged**
